module.exports = {
  rivets: 'blikblum/rivets#svelte',
  'rivets-backbone-adapter': 'blikblum/rivets-backbone-adapter#svelte',
  'html-loader': '^0.4.5',
  'incremental-dom': '^0.5.1',
  'superviews.js': '^3.0.4',
  'superviews-loader': '^0.0.5',
  snabbdom: '^0.6.9',
  'virtual-dom': '^2.1.1',
  'hyperscript-helpers': '^3.0.3',
  'virtual-dom-handlebars-loader': 'kohver/virtual-dom-handlebars-loader',
  'virtual-dom-handlebars': '^0.0.5',
  'incremental-bars': '^1.0.5',
  'handlebars': '^4.0.10',
  'incremental-bars-loader': '^0.1.0',
  'virtual-dom-loader': '^0.1.0',
  'virtual-jade-loader': '^0.5.0',
  'snabbdom': '^0.6.9',
  'snabbdom-helpers': '^4.0.1',
  'snabbdom-pragma': '^2.3.0',
  'inferno': '^3.4.3',
  'babel-plugin-inferno': '^3.2.0'
}