module.exports = {
  'backbone-computedfields': '^0.0.12',
  'backbone.localstorage': '^1.1.16',
  'backbone.validation': '^0.14.0',
  'tinybind': '^0.11.0',
  'tinybind-backbone-adapter': '^1.0.0',
  'html-loader': '^0.4.5',
  'incremental-dom': '^0.5.1',  
  'virtual-dom': '^2.1.1',
  'hyperscript-helpers': '^3.0.3',
  'virtual-dom-handlebars-loader': 'kohver/virtual-dom-handlebars-loader',
  'virtual-dom-handlebars': '^0.0.5',
  'incremental-bars': '^1.0.5',
  'handlebars': '^4.0.10',
  'incremental-bars-loader': '^0.1.0',
  'virtual-dom-loader': '^0.1.0',
  'virtual-jade-loader': '^0.5.0',
  'snabbdom': '^0.7.1',
  'snabbdom-helpers': '^4.0.1',
  'snabbdom-pragma-lite': '^3.1.0',
  'babel-plugin-transform-react-jsx': '^6.24.1',
  'babel-plugin-jsx-pragmatic': '^1.0.2',
  'inferno': '^3.4.3',
  'babel-plugin-inferno': '^3.2.0',
  'bootstrap3': {
    name: 'bootstrap-sass',
    version: '^3.3.7'
  },
  'bootstrap4': {
    name: 'bootstrap',
    version: '^4.1.1'
  },
  'bottlejs': '^1.7.1',
  'popper.js': '^1.12.9',
  'font-awesome': '^4.7.0',
  'url-loader': '^1.0.1',
  'file-loader': '^1.1.11',
  'imports-loader': '^0.8.0',
  'marionette.modalservice': '^0.6.0',
  'marionette.native': '^0.6.0',
  'marionette.routing': '^0.9.0',
  'radio.service': '^0.6.0',
  'framework7': '^2.3.1',
  'marionette.f7': '^2.0.1'
}
